### ISSUE TITLE
Error when running `docker compose up`

### ISSUE THREAD

**Issue by jpzhangvincent** [run-llama/sec-insights#13]
Got this error message when running the command `docker compose up`. It seems it's complaining the server connection? How to troubleshoot this issue? Thanks!

```
backend-llama-app-fastapi-1  | Running in AppEnvironment: local
backend-llama-app-fastapi-1  | 2023-09-09 20:17:43,336 [MainThread  ] [INFO ]  Set up logging with log level 10
backend-llama-app-fastapi-1  | 2023-09-09 20:17:43,336 [MainThread  ] [INFO ]  Skipping Sentry setup
backend-llama-app-fastapi-1  | 2023-09-09 20:17:43,336 [MainThread  ] [DEBUG]  Skipping migrations
backend-llama-app-fastapi-1  | INFO:     Will watch for changes in these directories: ['/app']
backend-llama-app-fastapi-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
backend-llama-app-fastapi-1  | INFO:     Started reloader process [1] using StatReload
backend-llama-app-fastapi-1  | INFO:     Started server process [20]
backend-llama-app-fastapi-1  | INFO:     Waiting for application startup.
backend-llama-app-fastapi-1  | ERROR:    Traceback (most recent call last):
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
backend-llama-app-fastapi-1  |     self._dbapi_connection = engine.raw_connection()
backend-llama-app-fastapi-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
backend-llama-app-fastapi-1  |     return self.pool.connect()
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
backend-llama-app-fastapi-1  |     return _ConnectionFairy._checkout(self)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
backend-llama-app-fastapi-1  |     fairy = _ConnectionRecord.checkout(pool)
backend-llama-app-fastapi-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
backend-llama-app-fastapi-1  |     rec = pool._do_get()
backend-llama-app-fastapi-1  |           ^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
backend-llama-app-fastapi-1  |     with util.safe_reraise():
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
backend-llama-app-fastapi-1  |     raise exc_value.with_traceback(exc_tb)
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
backend-llama-app-fastapi-1  |     return self._create_connection()
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
backend-llama-app-fastapi-1  |     return _ConnectionRecord(self)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
backend-llama-app-fastapi-1  |     self.__connect()
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
backend-llama-app-fastapi-1  |     with util.safe_reraise():
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
backend-llama-app-fastapi-1  |     raise exc_value.with_traceback(exc_tb)
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
backend-llama-app-fastapi-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
backend-llama-app-fastapi-1  |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
backend-llama-app-fastapi-1  |     return dialect.connect(*cargs, **cparams)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 615, in connect
backend-llama-app-fastapi-1  |     return self.loaded_dbapi.connect(*cargs, **cparams)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
backend-llama-app-fastapi-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  | psycopg2.OperationalError: could not connect to server: Connection refused
backend-llama-app-fastapi-1  | 	Is the server running on host "127.0.0.1" and accepting
backend-llama-app-fastapi-1  | 	TCP/IP connections on port 5432?
backend-llama-app-fastapi-1  |
backend-llama-app-fastapi-1  |
backend-llama-app-fastapi-1  | The above exception was the direct cause of the following exception:
backend-llama-app-fastapi-1  |
backend-llama-app-fastapi-1  | Traceback (most recent call last):
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
backend-llama-app-fastapi-1  |     async with self.lifespan_context(app) as maybe_state:
backend-llama-app-fastapi-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
backend-llama-app-fastapi-1  |     return await anext(self.gen)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/app/app/main.py", line 73, in lifespan
backend-llama-app-fastapi-1  |     if not check_current_head(cfg, engine):
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/app/app/main.py", line 26, in check_current_head
backend-llama-app-fastapi-1  |     with connectable.begin() as connection:
backend-llama-app-fastapi-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
backend-llama-app-fastapi-1  |     return next(self.gen)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3228, in begin
backend-llama-app-fastapi-1  |     with self.connect() as conn:
backend-llama-app-fastapi-1  |          ^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3264, in connect
backend-llama-app-fastapi-1  |     return self._connection_cls(self)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 147, in __init__
backend-llama-app-fastapi-1  |     Connection._handle_dbapi_exception_noconnection(
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2426, in _handle_dbapi_exception_noconnection
backend-llama-app-fastapi-1  |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
backend-llama-app-fastapi-1  |     self._dbapi_connection = engine.raw_connection()
backend-llama-app-fastapi-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3288, in raw_connection
backend-llama-app-fastapi-1  |     return self.pool.connect()
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 452, in connect
backend-llama-app-fastapi-1  |     return _ConnectionFairy._checkout(self)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1267, in _checkout
backend-llama-app-fastapi-1  |     fairy = _ConnectionRecord.checkout(pool)
backend-llama-app-fastapi-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 716, in checkout
backend-llama-app-fastapi-1  |     rec = pool._do_get()
backend-llama-app-fastapi-1  |           ^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 169, in _do_get
backend-llama-app-fastapi-1  |     with util.safe_reraise():
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
backend-llama-app-fastapi-1  |     raise exc_value.with_traceback(exc_tb)
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 167, in _do_get
backend-llama-app-fastapi-1  |     return self._create_connection()
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 393, in _create_connection
backend-llama-app-fastapi-1  |     return _ConnectionRecord(self)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 678, in __init__
backend-llama-app-fastapi-1  |     self.__connect()
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 902, in __connect
backend-llama-app-fastapi-1  |     with util.safe_reraise():
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
backend-llama-app-fastapi-1  |     raise exc_value.with_traceback(exc_tb)
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 898, in __connect
backend-llama-app-fastapi-1  |     self.dbapi_connection = connection = pool._invoke_creator(self)
backend-llama-app-fastapi-1  |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 637, in connect
backend-llama-app-fastapi-1  |     return dialect.connect(*cargs, **cparams)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 615, in connect
backend-llama-app-fastapi-1  |     return self.loaded_dbapi.connect(*cargs, **cparams)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
backend-llama-app-fastapi-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
backend-llama-app-fastapi-1  | 	Is the server running on host "127.0.0.1" and accepting
backend-llama-app-fastapi-1  | 	TCP/IP connections on port 5432?
backend-llama-app-fastapi-1  |
backend-llama-app-fastapi-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
backend-llama-app-fastapi-1  |
backend-llama-app-fastapi-1  | ERROR:    Application startup failed. Exiting.
```

**Comment by sourabhdesai** [comment]
Hi @jpzhangvincent , yeah this is an annoying issue :/ For now I'd give you the same recommendation I gave someone else that ran into this problem on [this issue](https://github.com/run-llama/sec-insights/issues/2). I'll look into seeing what I can do to work around this soon

**Comment by siddarthreddygsr** [comment]
I would like to work on this issue.

**Comment by JeroenJADS** [comment]
This doesn't actually matter to much. After you've done a `docker compose up`, just press `ctrl + c` and run `make run` should work!

**Comment by siddarthreddygsr** [comment]
> This doesn't actually matter to much. After you've done a `docker compose up`, just press `ctrl + c` and run `make run` should work!

Yeah that should do the job because it spins up the database and the localstack individually. As db is spun first it would have enough time to start before the localstack loads and tries to connect to connect to the database. But using ` docker compose up ` and checking if the DB is ready while connecting to it is the right way, especially if you're considering scaling.

**Comment by sourabhdesai** [comment]
@siddarthreddygsr  @JeroenJADS @jpzhangvincent we just merged in @siddarthreddygsr 's PR for this issue. That should get rid of the race condition between the db container and the backend container as the backend container will just wait until the db is ready for connection!

Thanks @siddarthreddygsr for taking this up!

**Comment by cosminro** [comment]
I still get the error, just rebased
```
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
backend-llama-app-fastapi-1  |  Is the server running on host "127.0.0.1" and accepting
backend-llama-app-fastapi-1  |  TCP/IP connections on port 5432?
backend-llama-app-fastapi-1  | 
backend-llama-app-fastapi-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
backend-llama-app-fastapi-1  | 
backend-llama-app-fastapi-1  | ERROR:    Application startup failed. Exitinbackend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  | sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
backend-llama-app-fastapi-1  |  Is the server running on host "127.0.0.1" and accepting
backend-llama-app-fastapi-1  |  TCP/IP connections on port 5432?
backend-llama-app-fastapi-1  | 
backend-llama-app-fastapi-1  | (Background on this error at: https://sqlalche.me/e/20/e3q8)
backend-llama-app-fastapi-1  | 
backend-llama-app-fastapi-1  | ERROR:    Application startup failed. Exitin
```
