### ISSUE TITLE
Error when running `make migrate`

### ISSUE THREAD

**Issue by jpzhangvincent** [run-llama/sec-insights#14]
Here is the error log:

```
(llama-app-backend-py3.11) bash-3.2$ make migrate
echo "Running migrations."
Running migrations.
docker compose start db
[+] Running 1/1
 ✔ Container backend-db-1  Started                                                                                             0.3s
poetry run python -m alembic upgrade head
The currently activated Python version 3.9.16 is not supported by the project (^3.10).
Trying to find and use a compatible version.
Using python3 (3.11.5)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llama-app-backend-cPGORASJ-py3.11/lib/python3.11/site-packages/alembic/__main__.py", line 4, in <module>
    main(prog="alembic")
  File "/Users.../Library/Caches/pypoetry/virtualenvs/llama-app-backend-cPGORASJ-py3.11/lib/python3.11/site-packages/alembic/config.py", line 630, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llama-app-backend-cPGORASJ-py3.11/lib/python3.11/site-packages/alembic/config.py", line 624, in main
    self.run_cmd(cfg, options)
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llama-app-backend-cPGORASJ-py3.11/lib/python3.11/site-packages/alembic/config.py", line 601, in run_cmd
    fn(
  File "/Users.../Library/Caches/pypoetry/virtualenvs/llama-app-backend-cPGORASJ-py3.11/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llama-app-backend-cPGORASJ-py3.11/lib/python3.11/site-packages/alembic/script/base.py", line 578, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llama-app-backend-cPGORASJ-py3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../Library/Caches/pypoetry/virtualenvs/llama-app-backend-cPGORASJ-py3.11/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/.../Desktop/jp_projects/ai_hackathons/sec-insights/backend/alembic/env.py", line 9, in <module>
    from app.core.config import settings
  File "/Users/.../Desktop/jp_projects/ai_hackathons/sec-insights/backend/app/core/config.py", line 169, in <module>
    settings = Settings()
               ^^^^^^^^^^
  File "pydantic/env_settings.py", line 40, in pydantic.env_settings.BaseSettings.__init__
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 7 validation errors for Settings
AWS_KEY
  field required (type=value_error.missing)
AWS_SECRET
  field required (type=value_error.missing)
POLYGON_IO_API_KEY
  field required (type=value_error.missing)
DATABASE_URL
  field required (type=value_error.missing)
S3_BUCKET_NAME
  field required (type=value_error.missing)
S3_ASSET_BUCKET_NAME
  field required (type=value_error.missing)
CDN_BASE_URL
  field required (type=value_error.missing)
make: *** [migrate] Error 1
```

**Comment by sourabhdesai** [comment]
Hi @jpzhangvincent , thanks for checking out the repo!

Looks like you need to set your environment variables. The first step to setting up the backend repo is to run `cp .env.development .env` and then load in the env vars in `.env` by running `set -a` followed by `source .env`.

After that, the service should technically start but certain endpoints won't work until you've properly set the API key and other secret parameters *(e.g. `OPENAI_API_KEY`, `AWS_KEY`, `AWS_SECRET` etc.)*. You'll need to create your own AWS, OpenAI, Polygon.io etc. accounts and get the API keys from those accounts into the `.env` file for the complete setup.

**Comment by jpzhangvincent** [comment]
Hmm but when I run in the codespace it didn't complain even when I didn't specify `AWS_KEY`/`AWS_SECRET`... but it throws the error and stop running due to the validator when I'm testing locally

**Comment by sourabhdesai** [comment]
Hmm not sure why that'd be the case actually 🤔 It certainly shouldn't start if you haven't set those environment variabels.

For what it's worth, if you're just trying to run migrations you can just set dummy values to many of those environment variables values like `xxx` as is done in [`.env.development` here](https://github.com/run-llama/sec-insights/blob/main/backend/.env.development#L9-L11).

**Comment by sourabhdesai** [comment]
Closing the issue as there's no follow-up. Please re-open if you continue having an issue related to this!
