### ISSUE TITLE
Not able to chat with my custom document

### ISSUE THREAD

**Issue by 345ishaan** [run-llama/sec-insights#19]
I tried added a custom document and chat with it but it doesn't process. Am i missing something in my local setup?

Here is the snippet of what i tried.
```
(llama-app-backend-py3.11) ➜  backend git:(main) ✗ make chat
poetry run python -m scripts.chat_llama
(Chat🦙) pick_docs
(Pick📄) help

Documented commands (type help <topic>):
========================================
fetch  finish  help  quit  select  select_id

(Pick📄) select_id 127b9132-e258-4b8d-96cb-f32eccd1a3e9
Selected document ID 127b9132-e258-4b8d-96cb-f32eccd1a3e9
(Pick📄) finish
(Chat🦙) help

Documented commands (type help <topic>):
========================================
create  delete  detail  help  message  pick_docs  quit

(Chat🦙) detail
No active conversation. Use CREATE to start a new conversation.
(Chat🦙) create
HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /api/conversation/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10178c7d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
Quitting.
(llama-app-backend-py3.11) ➜  backend git:(main) ✗ make chat
poetry run python -m scripts.chat_llama
(Chat🦙) pick_docs
(Pick📄) select_id 127b9132-e258-4b8d-96cb-f32eccd1a3e9
Selected document ID 127b9132-e258-4b8d-96cb-f32eccd1a3e9
(Pick📄) 
Selected document ID 127b9132-e258-4b8d-96cb-f32eccd1a3e9
(Pick📄) 
Selected document ID 127b9132-e258-4b8d-96cb-f32eccd1a3e9
(Pick📄) finish
(Chat🦙) create
Created conversation with ID 99e25e90-5593-47ce-8bb3-184e2a7744bc
(Chat🦙) message what is the tile of the paper?


=== Message 0 ===
{'id': '860ba40d-450e-4063-ab25-ed9cf6346d5e', 'created_at': '2023-09-10T20:29:44.087949', 'updated_at': '2023-09-10T20:29:44.087949', 'conversation_id': '99e25e90-5593-47ce-8bb3-184e2a7744bc', 'content': '', 'role': 'assistant', 'status': 'ERROR', 'sub_processes': []}


====== Final Message ======

(Chat🦙) 

```

**Comment by 345ishaan** [comment]
On a bit more investigation: I also saw that i am not able to open: http://localhost:8000/api/docs , so something wrong with my backend.

**Comment by sourabhdesai** [comment]
> On a bit more investigation: I also saw that i am not able to open: http://localhost:8000/api/docs , so something wrong with my backend.

The endpoint you're looking for is probably `http://localhost:8000/api/document`

If you open `http://localhost:8000/docs` in a browser you should see the OpenAPI spec for all the endpoints exposed by the service.

In general, yeah I agree there's likely something wrong with your local backend setup. I'd suggest at least making sure that you can get a successful response from `http://localhost:8000/api/document` before trying to insert your custom document.

If you haven't already seen it, our YouTube video has a [section here](https://youtu.be/2O52Tfj79T4?si=apRe2nRfMEWuk-T2&t=677) on setting up your local dev environment and another [section here](https://youtu.be/2O52Tfj79T4?si=_aGlPTUWJwUdyL1N&t=1310) on using custom documents. Hope those are helpful!

**Comment by sourabhdesai** [comment]
@345ishaan did you figure this out? Happy to help!

**Comment by 345ishaan** [comment]
> @345ishaan did you figure this out? Happy to help!

Sorry for the delay. I am now able to see response from both `http://localhost:8000/docs` and `http://localhost:8000/api/document`. I followed the steps here (https://github.com/run-llama/sec-insights/tree/main/backend#setup--usage-instructions) in my local setup which i think were needing to setup database for adding any custom document.

Let me check if I can now chat with my doc.

**Comment by 345ishaan** [comment]
> > @345ishaan did you figure this out? Happy to help!
> 
> Sorry for the delay. I am now able to see response from both `http://localhost:8000/docs` and `http://localhost:8000/api/document`. I followed the steps here (https://github.com/run-llama/sec-insights/tree/main/backend#setup--usage-instructions) in my local setup which i think were needing to setup database for adding any custom document.
> 
> Let me check if I can now chat with my doc.

hmm still not able to..
![Screen Shot 2023-09-13 at 9 08 36 PM](https://github.com/run-llama/sec-insights/assets/7318028/ff66f683-880b-4709-a2bb-6e538c28f784)

**Comment by 345ishaan** [comment]
> > > @345ishaan did you figure this out? Happy to help!
> > 
> > 
> > Sorry for the delay. I am now able to see response from both `http://localhost:8000/docs` and `http://localhost:8000/api/document`. I followed the steps here (https://github.com/run-llama/sec-insights/tree/main/backend#setup--usage-instructions) in my local setup which i think were needing to setup database for adding any custom document.
> > Let me check if I can now chat with my doc.
> 
> hmm still not able to.. ![Screen Shot 2023-09-13 at 9 08 36 PM](https://user-images.githubusercontent.com/7318028/267852885-ff66f683-880b-4709-a2bb-6e538c28f784.png)

I verified that document does exist:

![Screen Shot 2023-09-13 at 9 13 14 PM](https://github.com/run-llama/sec-insights/assets/7318028/30c3dedd-ab6d-4ee3-8dae-51ed14771941)

**Comment by 345ishaan** [comment]
> > > @345ishaan did you figure this out? Happy to help!
> > 
> > 
> > Sorry for the delay. I am now able to see response from both `http://localhost:8000/docs` and `http://localhost:8000/api/document`. I followed the steps here (https://github.com/run-llama/sec-insights/tree/main/backend#setup--usage-instructions) in my local setup which i think were needing to setup database for adding any custom document.
> > Let me check if I can now chat with my doc.
> 
> hmm still not able to.. ![Screen Shot 2023-09-13 at 9 08 36 PM](https://user-images.githubusercontent.com/7318028/267852885-ff66f683-880b-4709-a2bb-6e538c28f784.png)

checked it exists at [http:](http://localhost:8000/api/document/)

![Screen Shot 2023-09-13 at 9 15 51 PM](https://github.com/run-llama/sec-insights/assets/7318028/788f8174-e9f0-442e-ae7e-f5424b35b316)

**Comment by 345ishaan** [comment]
I tried selecting other document id's i.e 10ks which are added using the command in instruction to my local DB but it fails there as well.

**Comment by sourabhdesai** [comment]
Can you see what the backend error was when you tried chatting with that custom doc in the `make chat` REPL?

I have a hunch that there's a few documents in your `documents` table that link to document PDFs that don't actually exist in your S3 bucket. If that's the case, you may want to drop your documents table and re-run the migration script.

**Comment by 345ishaan** [comment]
![Screen Shot 2023-09-16 at 1 27 43 PM](https://github.com/run-llama/sec-insights/assets/7318028/c6c75f64-3d43-484f-ac2a-b83986bd2273)

document which i am creating chat on seems not being indexed properly

**Comment by sourabhdesai** [comment]
Can you sync your fork with the latest code on our repo? We [added a check here](https://github.com/run-llama/sec-insights/blob/main/backend/app/chat/engine.py#L278) last week to better support custom docs on the backend.

**Comment by 345ishaan** [comment]
Just resynced to latest. I think there is general issue in seeding the documents into the database. I ran `make seed_db_local` and got same error.

**Comment by 345ishaan** [comment]
@sourabhdesai I was able to get it to work by manually creating the DB i.e `aws --endpoint-url=http://localhost:4566 s3 mb s3://ig-backend-local`

not sure if I am missing any step in the setup which led to this.

Also, I upserted this document: `python scripts/upsert_document.py https://arxiv.org/pdf/2305.14314.pdf`
but when i try to chat with `message what is document about`, the response generation seems biased towards matching responses to finanical queries it seems: ```I apologize for the confusion, but it seems that the document you are referring to is not related to financial analysis or any specific company. It appears to be a document discussing a dataset and the approach used for training in the context of instruction following and natural language processing tasks. If you have any financial questions or if there's anything else I can assist you with, please let me know.```

**Comment by sourabhdesai** [comment]
@345ishaan Ah yeah you may need to some modifications to the prompts we're using for the SEC Insights use case. Try modifying the prompt strings at these locations in your fork:

* [Custom Response Synth prompt](https://github.com/run-llama/sec-insights/blob/e81c839/backend/app/chat/qa_response_synth.py#L15-L48)
* [Vector Index tool descriptions](https://github.com/run-llama/sec-insights/blob/e81c83958a428e2aa02e8cb1280c3a17c55c4aa9/backend/app/chat/engine.py#L295-L296)
* System Message ([template](https://github.com/run-llama/sec-insights/blob/e81c83958a428e2aa02e8cb1280c3a17c55c4aa9/backend/app/chat/constants.py#L3-L17) and [construction](https://github.com/run-llama/sec-insights/blob/e81c83958a428e2aa02e8cb1280c3a17c55c4aa9/backend/app/chat/engine.py#L336))
* [User Message Prefix](https://github.com/run-llama/sec-insights/blob/e81c83958a428e2aa02e8cb1280c3a17c55c4aa9/backend/app/chat/messaging.py#L143-L145)

Hopefully not missing other places that would need to be updated, but thats what I can recall from the top of my head 😅

**Comment by rbmdotdev** [comment]
I get the same issue

> ![Screen Shot 2023-09-16 at 1 27 43 PM](https://user-images.githubusercontent.com/7318028/268470027-c6c75f64-3d43-484f-ac2a-b83986bd2273.png)
> 
> document which i am creating chat on seems not being indexed properly

I get this same error when trying to run the make seed_db and make seed_db_local.

When I run the app I can see that the documents have been loaded and I can add the Microsoft and AMazon 10ks. for example, to a conversation and start it but when I try to chat with the docs the backend errors with the same exception

Failed to load indices from storage. Creating new indices.
Traceback (most recent call last):
  File "/workspaces/pdf-insights/backend/app/chat/engine.py", line 151, in build_doc_id_to_index_map
    indices = load_indices_from_storage(
  File "/home/codespace/.cache/pypoetry/virtualenvs/llama-app-backend-5nkqL5DH-py3.10/lib/python3.10/site-packages/llama_index/indices/loading.py", line 71, in load_indices_from_storage
    raise ValueError(f"Failed to load index with ID {index_id}")
ValueError: Failed to load index with ID 515694dc-13ac-41d0-ae28-e63125af8b94

**Comment by haokinglong** [comment]
> I get the same issue
> 
> > ![Screen Shot 2023-09-16 at 1 27 43 PM](https://user-images.githubusercontent.com/7318028/268470027-c6c75f64-3d43-484f-ac2a-b83986bd2273.png)
> > document which i am creating chat on seems not being indexed properly
> 
> I get this same error when trying to run the make seed_db and make seed_db_local.
> 
> When I run the app I can see that the documents have been loaded and I can add the Microsoft and AMazon 10ks. for example, to a conversation and start it but when I try to chat with the docs the backend errors with the same exception
> 
> ```
> Failed to load indices from storage. Creating new indices.
> Traceback (most recent call last):
>   File "/workspaces/pdf-insights/backend/app/chat/engine.py", line 151, in build_doc_id_to_index_map
>     indices = load_indices_from_storage(
>   File "/home/codespace/.cache/pypoetry/virtualenvs/llama-app-backend-5nkqL5DH-py3.10/lib/python3.10/site-packages/llama_index/indices/loading.py", line 71, in load_indices_from_storage
>     raise ValueError(f"Failed to load index with ID {index_id}")
> ValueError: Failed to load index with ID 515694dc-13ac-41d0-ae28-e63125af8b94
> ```
> 
> seems like the docs are making it into the db but not into the localstack s3 buckets, not sure how whether the index issue is causing them to not make it to the buckets or the fact they arent in the buckets is causing the index error

me too~

**Comment by sourabhdesai** [comment]
@rbmdotdev @haokinglong Yes this error message does show up when running the seed script. I recently made a change to make it clear that this error to be expected and not an issue if you're running from the seed script. The error that is being thrown is because the newly inserted document hasn't been indexed in the storage context yet. That error does logged into your terminal output but also does get caught. [Within the catch of the try/catch](https://github.com/run-llama/sec-insights/blob/main/backend/app/chat/engine.py#L158-L178), we run the indexing process for that document so that it effectively gets seeded into the storage context. I recently updated this error message to make it more clear that `If you're running the seed_db script, this is normal and expected`
