### ISSUE TITLE
docker compose up doesn't work

### ISSUE THREAD

**Issue by cosminro** [run-llama/sec-insights#24]
I'm following the instructions and the video step by step but I get this error even after the recent proposed fix.

git log output
```
commit 3e5d162e27687bda9d223851ff6c2b6e2b02ac69 (HEAD -> main, origin/main, origin/HEAD)
Author: Sourabh Desai <sourabhdesai@gmail.com>
Date:   Mon Sep 11 14:44:07 2023 -0700

    Bugfix/issue 13 (#23)
    
    * fixed typo in README
    
    * fixed docker compose bug #13
    
    * made requested changes

```

error log
```
backend-llama-app-fastapi-1  | Attempt 27: Database is not yet available. Error: [Errno 111] Connect call failed ('127.0.0.1', 5432)
backend-llama-app-fastapi-1  | Attempt 28: Database is not yet available. Error: [Errno 111] Connect call failed ('127.0.0.1', 5432)
backend-llama-app-fastapi-1  | Attempt 29: Database is not yet available. Error: [Errno 111] Connect call failed ('127.0.0.1', 5432)
backend-llama-app-fastapi-1  | Attempt 30: Database is not yet available. Error: [Errno 111] Connect call failed ('127.0.0.1', 5432)
backend-llama-app-fastapi-1  | ERROR:    Traceback (most recent call last):
backend-llama-app-fastapi-1  |   File "/app/app/db/wait_for_db.py", line 10, in check_database_connection
backend-llama-app-fastapi-1  |     await db.execute(text("SELECT 1"))
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 439, in execute
backend-llama-app-fastapi-1  |     result = await greenlet_spawn(
backend-llama-app-fastapi-1  |              ^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
backend-llama-app-fastapi-1  |     result = context.throw(*sys.exc_info())
backend-llama-app-fastapi-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/root/.cache/pypoetry/virtualenvs/llama-app-backend-9TtSrW0h-py3.11/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2246, in execute
```

```
backend-llama-app-fastapi-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
backend-llama-app-fastapi-1  |     return await anext(self.gen)
backend-llama-app-fastapi-1  |            ^^^^^^^^^^^^^^^^^^^^^
backend-llama-app-fastapi-1  |   File "/app/app/main.py", line 68, in lifespan
backend-llama-app-fastapi-1  |     await check_database_connection()
backend-llama-app-fastapi-1  |   File "/app/app/db/wait_for_db.py", line 16, in check_database_connection
backend-llama-app-fastapi-1  |     raise ValueError(
backend-llama-app-fastapi-1  | ValueError: Couldn't connect to database after 30 attempts.
backend-llama-app-fastapi-1  | 
backend-llama-app-fastapi-1  | 
backend-llama-app-fastapi-1  | ERROR:    Application startup failed. Exiting.
backend-db-1                 | 2023-09-11 22:31:10.634 UTC [27] LOG:  checkpoint starting: time
backend-db-1                 | 2023-09-11 22:31:10.748 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s)
```

**Comment by sourabhdesai** [comment]
@cosminro thanks for trying out the fix!

Do you see that the DB container actually started correctly? May also be worth doing a full rebuild of your containers with `docker compose up --build` 🤞

Regardless, for local development you may want to use `make run` instead of `docker compose up` anyways. I've found it's easier to use debugging tools like `pdb` with `make run` which runs the backend directly on your OS rather than within a container.

**Comment by sourabhdesai** [comment]
Chatted on discord, sounds like you figured this out 👌 closing but re-open if needed
