### ISSUE TITLE
Updating llama-index from v0.8.13 via `poetry lock` breaks the backend

### ISSUE THREAD

**Issue by joshsabol46** [run-llama/sec-insights#62]
### Steps to reproduce:

1. run `poetry shell`
2. run `poetry lock`
3. confirm poetry.lock file has updates. For example, latest for me is:
  ```
  [[package]]
  name = "llama-index"
  version = "0.8.42"
  description = "Interface between LLMs and your data"
  optional = false
  python-versions = "*"
  files = [
      {file = "llama_index-0.8.42-py3-none-any.whl", hash = "sha256:08720554ceaef169e1a151f4fd982c0555703e85b23bf0dbf290d9dc0605655d"},
      {file = "llama_index-0.8.42.tar.gz", hash = "sha256:14cca43188d9afd058d74c5574e745dc937e724a20576a9ef81967b9f2659b03"},
  ]
  ```
4. run `poetry install` and steps 5-7 in /backend README
5. start a chat, ask a question, result is infinite loop of the same question and this server log error:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 552, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 287, in __await__
    yield self  # This tells Task to wait for completion.
    ^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
asyncpg.exceptions.InvalidTextRepresentationError: invalid input value for enum "MessageSubProcessSourceEnum": "AGENT_STEP"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2112, in _exec_insertmany_context
    dialect.do_execute(
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 586, in execute
    self._adapt_connection.await_(
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 564, in _prepare_and_execute
    self._handle_exception(error)
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 515, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/Users/joshuasabol/.local/share/virtualenvs/HealthKey-ZlgcgJrM/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 803, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.Error: <class 'asyncpg.exceptions.InvalidTextRepresentationError'>: invalid input value for enum "MessageSubProcessSourceEnum": "AGENT_STEP"

The above exception was the direct cause of the following exception:
...
...
...
```

### Steps to Resolt

Simple solution is to revert back to `  version = "0.8.13"`.

### Request

Can we update SEC-Insights to support the latest llama-index version?

**Comment by sourabhdesai** [comment]
@joshsabol46 thanks for raising this! Just merged [this PR](https://github.com/run-llama/sec-insights/pull/66) which updates the project to use the current latest version of llama-index (`0.8.55`). Feel free to re-open if you see any further issues!
