### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by PapaRedNinjago** [run-llama/sec-insights#83]
Hello, when I run the chat test, I have the following message:

(Chat🦙) message Hi
====== Final Message ======
Sorry, I either wasn't able to understand your question or I don't have an answer for it.
(Chat🦙) 

**and in the backend terminal I have the following:**

**INFO:     127.0.0.1:33006 - "GET /api/conversation/a2d5e482-a251-4d36-8c63-66bde3418919/message?user_message=Hi HTTP/1.1" 200 OK
STARTING TURN 1
---------------**

Tried sending SubProcess event (source=MessageSubProcessSourceEnum.AGENT_STEP) after channel was closed
Traceback (most recent call last):
  File "/workspaces/sec-insights/backend/app/chat/messaging.py", line 106, in async_on_event
    await self._send_chan.send(
  File "/root/.cache/pypoetry/virtualenvs/llama-app-backend--Qk0ygDj-py3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 213, in send
    self.send_nowait(item)
  File "/root/.cache/pypoetry/virtualenvs/llama-app-backend--Qk0ygDj-py3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 195, in send_nowait
    raise ClosedResourceError
anyio.ClosedResourceError

Thank you

**Comment by PapaRedNinjago** [comment]
Update on the last post.
I made it work by recreating a new codespace from the original project.

**Comment by namtho7078** [comment]
sorry what did you do to fix this ?
